/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const WristbandsLazyRouteImport = createFileRoute('/wristbands')()
const IndexLazyRouteImport = createFileRoute('/')()

const WristbandsLazyRoute = WristbandsLazyRouteImport.update({
  id: '/wristbands',
  path: '/wristbands',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/wristbands.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/wristbands': typeof WristbandsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/wristbands': typeof WristbandsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/wristbands': typeof WristbandsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wristbands'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wristbands'
  id: '__root__' | '/' | '/wristbands'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  WristbandsLazyRoute: typeof WristbandsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wristbands': {
      id: '/wristbands'
      path: '/wristbands'
      fullPath: '/wristbands'
      preLoaderRoute: typeof WristbandsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  WristbandsLazyRoute: WristbandsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
